services:
  - type: web
    name: greenapi-image-pdf-relay
    env: python
    plan: free
    region: oregon
    autoDeploy: true
    buildCommand: |
      pip install -r requirements.txt
      cd whatsapp_gateway && npm install
    startCommand: uvicorn app.main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.9
      - key: CHROME_PATH
        value: /usr/bin/chromium
      - key: GREEN_API_BASE_URL
        value: http://127.0.0.1:3000
      - key: WHATSAPP_MODE
        value: local
      # Set the following securely in the Render Dashboard after creating the service:
      # - GREEN_API_INSTANCE_ID
      # - GREEN_API_API_TOKEN
      # - ADMIN_CHAT_ID
      # - ADMIN_PASSWORD (optional, for /ui protection)
      # - GEMINI_API_KEY (required for LLM features)
      # - GEMINI_MODEL (optional)
    disk:
      name: storage
      mountPath: /opt/render/project/src/storage
      sizeGB: 1
    healthCheckPath: /health
    # Install native packages required by yt-dlp for some operations and headless Chromium for whatsapp-web.js
    # See https://render.com/docs/native-dependencies
    aptPackages:
      - ffmpeg
      - chromium
      - libnss3
      - libatk1.0-0
      - libatk-bridge2.0-0
      - libx11-6
      - libx11-xcb1
      - libxcomposite1
      - libxdamage1
      - libxext6
      - libxfixes3
      - libxcb1
      - libxcb-dri3-0
      - libxrandr2
      - libgbm1
      - libasound2
      - libcups2
      - libdrm2
      - libxshmfence1